knpu_oauth2_client:
    clients:
        generic:
            type: generic
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            client_id: '%env(OAUTH_LARAVEL_CLIENT_ID)%'
            client_secret: '%env(OAUTH_LARAVEL_CLIENT_SECRET)%'
            provider_options:
                urlAuthorize: '%env(OAUTH_LARAVEL_AUTHORIZE_URL)%'
                urlAccessToken: '%env(OAUTH_LARAVEL_TOKEN_URL)%'
                urlResourceOwnerDetails: '%env(OAUTH_LARAVEL_USER_URL)%'
                responseResourceOwnerId: 'sub'
            redirect_route: chamilo.oauth2_generic_check

        facebook:
            type: facebook
            client_id: ''
            client_secret: ''
            redirect_route: chamilo.oauth2_facebook_check
            graph_api_version: 'v20.0'

        keycloak:
            type: keycloak
            client_id: ''
            client_secret: ''
            redirect_route: chamilo.oauth2_keycloak_check
            auth_server_url: null
            realm: null

        azure:
            type: azure
            client_id: ''
            redirect_route: chamilo.oauth2_azure_check
            client_secret: ' '

        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
